services:
  php:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: php -S 0.0.0.0:8000 -t public
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cesizen
    ports:
      - "3306:3306"
